//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFlowResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeFlowResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code created!.
        /// </summary>
        public static string CodeCreated {
            get {
                return ResourceManager.GetString("CodeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code search.
        /// </summary>
        public static string CodeSearch {
            get {
                return ResourceManager.GetString("CodeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Manual code entrie(s) | {1} Conflicts.
        /// </summary>
        public static string CommitEntries {
            get {
                return ResourceManager.GetString("CommitEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to add this profile?.
        /// </summary>
        public static string ConfirmAdd {
            get {
                return ResourceManager.GetString("ConfirmAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to commit all selected non conflict code in the list to Genio?.
        /// </summary>
        public static string ConfirmationExport {
            get {
                return ResourceManager.GetString("ConfirmationExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this manual code?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to commit this manual code?.
        /// </summary>
        public static string ConfirmExportDirect {
            get {
                return ResourceManager.GetString("ConfirmExportDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to update this profile?.
        /// </summary>
        public static string ConfirmUpdate {
            get {
                return ResourceManager.GetString("ConfirmUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict.
        /// </summary>
        public static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genio profile.
        /// </summary>
        public static string ConnectDB {
            get {
                return ResourceManager.GetString("ConnectDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection open!.
        /// </summary>
        public static string ConnectionOpen {
            get {
                return ResourceManager.GetString("ConnectionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing some options in your manual code!.
        /// </summary>
        public static string CreateError {
            get {
                return ResourceManager.GetString("CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create in genio.
        /// </summary>
        public static string CreateInGenio {
            get {
                return ResourceManager.GetString("CreateInGenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to use desired tool. Please check your custom tool options..
        /// </summary>
        public static string CustomToolError {
            get {
                return ResourceManager.GetString("CustomToolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create to profile.
        ///Please make sure profile name is unique, database and server names are valid and that the genio path is correct..
        /// </summary>
        public static string ErrorAddProfile {
            get {
                return ResourceManager.GetString("ErrorAddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while comparing code!.
        /// </summary>
        public static string ErrorComparing {
            get {
                return ResourceManager.GetString("ErrorComparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server {0}!
        ///{1}.
        /// </summary>
        public static string ErrorConnect {
            get {
                return ResourceManager.GetString("ErrorConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create code in Genio!
        ///{0}.
        /// </summary>
        public static string ErrorCreate {
            get {
                return ResourceManager.GetString("ErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete your request!
        ///{0}.
        /// </summary>
        public static string ErrorRequest {
            get {
                return ResourceManager.GetString("ErrorRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while resolving conflict!
        ///{0}.
        /// </summary>
        public static string ErrorResolvingConflict {
            get {
                return ResourceManager.GetString("ErrorResolvingConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to search for given terms!
        ///{0}.
        /// </summary>
        public static string ErrorSearch {
            get {
                return ResourceManager.GetString("ErrorSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A server and database must be selected!.
        /// </summary>
        public static string ErrorSelectDB {
            get {
                return ResourceManager.GetString("ErrorSelectDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse system info.
        ///{0}.
        /// </summary>
        public static string ErrorSystemInfo {
            get {
                return ResourceManager.GetString("ErrorSystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating manual code!
        ///{0}.
        /// </summary>
        public static string ErrorUpdating {
            get {
                return ResourceManager.GetString("ErrorUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit merged code?.
        /// </summary>
        public static string ExportedMerged {
            get {
                return ResourceManager.GetString("ExportedMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Manwins xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///&lt;!-- NOTA: Na descrição e exemplo podem usar \r\n para fazer mudança da linha --&gt;
        ///&lt;!-- Sintaxe especifico do Destino: --&gt;
        ///&lt;!-- NOTA: [SIS] substituido por sigla dos clientes --&gt;
        ///&lt;!-- NOTA: [TABS] substituido por todos NDBF das tabelas --&gt;
        ///&lt;!-- NOTA: O wildcard do Destino deve ser sempre relativo a partir do root do tipo da geração --&gt;
        /// &lt;Platforms&gt;
        ///		&lt;Platform&gt;
        ///			&lt;Ident [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ManwinInfoData {
            get {
                return ResourceManager.GetString("ManwinInfoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes found..
        /// </summary>
        public static string NoChanges {
            get {
                return ResourceManager.GetString("NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to commit!.
        /// </summary>
        public static string NotSubmited {
            get {
                return ResourceManager.GetString("NotSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed..
        /// </summary>
        public static string OperationComplete {
            get {
                return ResourceManager.GetString("OperationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected profile is a development environment and its Genio version is {0}..
        /// </summary>
        public static string ProfileDev {
            get {
                return ResourceManager.GetString("ProfileDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected profile is a production environment and its Genio version is {0}..
        /// </summary>
        public static string ProfileProd {
            get {
                return ResourceManager.GetString("ProfileProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database version from selected profile is {0}.
        /// </summary>
        public static string ProfileVersion {
            get {
                return ResourceManager.GetString("ProfileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution version is {0} and the version of the selected profile is {1}..
        /// </summary>
        public static string SolutionVersion {
            get {
                return ResourceManager.GetString("SolutionVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code commited.
        /// </summary>
        public static string Submited {
            get {
                return ResourceManager.GetString("Submited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute operation!
        ///{0}.
        /// </summary>
        public static string UnableToExecuteOperation {
            get {
                return ResourceManager.GetString("UnableToExecuteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual code not found in database!
        ///Verify your profile.
        /// </summary>
        public static string VerifyProfile {
            get {
                return ResourceManager.GetString("VerifyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Solution version is different from the selected profile!.
        /// </summary>
        public static string WarningProfile {
            get {
                return ResourceManager.GetString("WarningProfile", resourceCulture);
            }
        }
    }
}
