//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFlow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeFlow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap action_add_16xLG {
            get {
                object obj = ResourceManager.GetObject("action_add_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add_grey_16x {
            get {
                object obj = ResourceManager.GetObject("Add_grey_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddFile_16x {
            get {
                object obj = ResourceManager.GetObject("AddFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddUser_16x {
            get {
                object obj = ResourceManager.GetObject("AddUser_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_merge_16xLG {
            get {
                object obj = ResourceManager.GetObject("arrow_merge_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel_16x {
            get {
                object obj = ResourceManager.GetObject("Cancel_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CaseSensitive_16x {
            get {
                object obj = ResourceManager.GetObject("CaseSensitive_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Checkmark_16x {
            get {
                object obj = ResourceManager.GetObject("Checkmark_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close_16xLG {
            get {
                object obj = ResourceManager.GetObject("Close_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CodeActivity_16x {
            get {
                object obj = ResourceManager.GetObject("CodeActivity_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code created!.
        /// </summary>
        internal static string CodeCreated {
            get {
                return ResourceManager.GetString("CodeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code search.
        /// </summary>
        internal static string CodeSearch {
            get {
                return ResourceManager.GetString("CodeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Manual code entrie(s) | {1} Conflicts.
        /// </summary>
        internal static string CommitEntries {
            get {
                return ResourceManager.GetString("CommitEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Compare_16x {
            get {
                object obj = ResourceManager.GetObject("Compare_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to add this profile?.
        /// </summary>
        internal static string ConfirmAdd {
            get {
                return ResourceManager.GetString("ConfirmAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to commit all selected non conflict code in the list to Genio?.
        /// </summary>
        internal static string ConfirmationExport {
            get {
                return ResourceManager.GetString("ConfirmationExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to commit this manual code?.
        /// </summary>
        internal static string ConfirmExportDirect {
            get {
                return ResourceManager.GetString("ConfirmExportDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to update this profile?.
        /// </summary>
        internal static string ConfirmUpdate {
            get {
                return ResourceManager.GetString("ConfirmUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict.
        /// </summary>
        internal static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Conflict_16x {
            get {
                object obj = ResourceManager.GetObject("Conflict_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genio profile.
        /// </summary>
        internal static string ConnectDB {
            get {
                return ResourceManager.GetString("ConnectDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection open!.
        /// </summary>
        internal static string ConnectionOpen {
            get {
                return ResourceManager.GetString("ConnectionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing some options in your manual code!.
        /// </summary>
        internal static string CreateError {
            get {
                return ResourceManager.GetString("CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create in genio.
        /// </summary>
        internal static string CreateInGenio {
            get {
                return ResourceManager.GetString("CreateInGenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to use desired tool. Please check your custom tool options..
        /// </summary>
        internal static string CustomToolError {
            get {
                return ResourceManager.GetString("CustomToolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteUser_16x {
            get {
                object obj = ResourceManager.GetObject("DeleteUser_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Download_grey {
            get {
                object obj = ResourceManager.GetObject("Download_grey", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download_grey_16x {
            get {
                object obj = ResourceManager.GetObject("Download_grey_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DownloadFile_16x {
            get {
                object obj = ResourceManager.GetObject("DownloadFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name must be unique!.
        /// </summary>
        internal static string ErrorAddProfile {
            get {
                return ResourceManager.GetString("ErrorAddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while comparing code!.
        /// </summary>
        internal static string ErrorComparing {
            get {
                return ResourceManager.GetString("ErrorComparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server {0}!
        ///{1}.
        /// </summary>
        internal static string ErrorConnect {
            get {
                return ResourceManager.GetString("ErrorConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create code in Genio!
        ///{0}.
        /// </summary>
        internal static string ErrorCreate {
            get {
                return ResourceManager.GetString("ErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete your request!
        ///{0}.
        /// </summary>
        internal static string ErrorRequest {
            get {
                return ResourceManager.GetString("ErrorRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while resolving conflict!
        ///{0}.
        /// </summary>
        internal static string ErrorResolvingConflict {
            get {
                return ResourceManager.GetString("ErrorResolvingConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to search for given terms!
        ///{0}.
        /// </summary>
        internal static string ErrorSearch {
            get {
                return ResourceManager.GetString("ErrorSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A server and database must be selected!.
        /// </summary>
        internal static string ErrorSelectDB {
            get {
                return ResourceManager.GetString("ErrorSelectDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating manual code!
        ///{0}.
        /// </summary>
        internal static string ErrorUpdating {
            get {
                return ResourceManager.GetString("ErrorUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Event {
            get {
                object obj = ResourceManager.GetObject("Event", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Event_16x {
            get {
                object obj = ResourceManager.GetObject("Event_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit merged code?.
        /// </summary>
        internal static string ExportedMerged {
            get {
                return ResourceManager.GetString("ExportedMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon genio {
            get {
                object obj = ResourceManager.GetObject("genio", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Join_16x {
            get {
                object obj = ResourceManager.GetObject("Join_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Manwins xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///&lt;!-- NOTA: Na descrição e exemplo podem usar \r\n para fazer mudança da linha --&gt;
        ///&lt;!-- Sintaxe especifico do Destino: --&gt;
        ///&lt;!-- NOTA: [SIS] substituido por sigla dos clientes --&gt;
        ///&lt;!-- NOTA: [TABS] substituido por todos NDBF das tabelas --&gt;
        ///&lt;!-- NOTA: O wildcard do Destino deve ser sempre relativo a partir do root do tipo da geração --&gt;
        /// &lt;Platforms&gt;
        ///		&lt;Platform&gt;
        ///			&lt;Ident [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManwinInfoData {
            get {
                return ResourceManager.GetString("ManwinInfoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to commit code!.
        /// </summary>
        internal static string NotSubmited {
            get {
                return ResourceManager.GetString("NotSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PreviewWebTab_16x {
            get {
                object obj = ResourceManager.GetObject("PreviewWebTab_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected profile is a development environment and its Genio version is {0}..
        /// </summary>
        internal static string ProfileDev {
            get {
                return ResourceManager.GetString("ProfileDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected profile is a production environment and its Genio version is {0}..
        /// </summary>
        internal static string ProfileProd {
            get {
                return ResourceManager.GetString("ProfileProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database version from selected profile is {0}.
        /// </summary>
        internal static string ProfileVersion {
            get {
                return ResourceManager.GetString("ProfileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_16xLG {
            get {
                object obj = ResourceManager.GetObject("refresh_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Refresh_grey {
            get {
                object obj = ResourceManager.GetObject("Refresh_grey", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh_grey_16x {
            get {
                object obj = ResourceManager.GetObject("Refresh_grey_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_16xLG {
            get {
                object obj = ResourceManager.GetObject("save_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search_16x {
            get {
                object obj = ResourceManager.GetObject("Search_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Search1 {
            get {
                object obj = ResourceManager.GetObject("Search1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution version is {0} and the version of the selected profile is {1}..
        /// </summary>
        internal static string SolutionVersion {
            get {
                return ResourceManager.GetString("SolutionVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartupProject_16x {
            get {
                object obj = ResourceManager.GetObject("StartupProject_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code commited.
        /// </summary>
        internal static string Submited {
            get {
                return ResourceManager.GetString("Submited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Synchronize_16x {
            get {
                object obj = ResourceManager.GetObject("Synchronize_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Team_16x {
            get {
                object obj = ResourceManager.GetObject("Team_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute desired operation!
        ///{0}.
        /// </summary>
        internal static string UnableToExecute {
            get {
                return ResourceManager.GetString("UnableToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Upload_gray_16x {
            get {
                object obj = ResourceManager.GetObject("Upload_gray_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UploadFile_16x {
            get {
                object obj = ResourceManager.GetObject("UploadFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserTrigger_16x {
            get {
                object obj = ResourceManager.GetObject("UserTrigger_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual code not found in database!
        ///Verify your profile.
        /// </summary>
        internal static string VerifyProfile {
            get {
                return ResourceManager.GetString("VerifyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Solution version is different from the selected profile!.
        /// </summary>
        internal static string WarningProfile {
            get {
                return ResourceManager.GetString("WarningProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WholeWordMatch_16x {
            get {
                object obj = ResourceManager.GetObject("WholeWordMatch_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
